In [1]:
import numpy as np

In [9]:
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [10]:
type(a1)

numpy.ndarray

In [13]:
a2=np.array([[1,2,3],[4,5,6]])
a3=np.array([[1, 2, 3],[4,5,6], [8,9,10]])

In [16]:
a2


numpy.ndarray

In [17]:
a3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [18]:
a1.shape

(3,)

In [19]:
a1.size


3

In [20]:
type(a1)

numpy.ndarray

In [22]:
import pandas as pd


In [23]:
df=pd.DataFrame(a2)

In [24]:
df


0  1  2
0  1  2  3
1  4  5  6

##Creating arrays

##Hello

# Hello|

# Creating arrays

In [27]:
sample_array=np.array([1,2,3])
sample_array

array([1, 2, 3])

In [28]:
sample_array.dtype


dtype('int32')

In [30]:
ones=np.ones((2,3))

In [31]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
ones.dtype

dtype('float64')

In [34]:
zeros=np.zeros((2,3))

In [35]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [37]:
range_array= np.arange(0, 10 , 2)

In [38]:
range_array

array([0, 2, 4, 6, 8])

In [41]:
random_array=np.random.randint(0,10,size=(3,5))
random_array

array([[5, 0, 2, 0, 6],
       [0, 8, 0, 0, 9],
       [9, 2, 5, 3, 5]])

In [43]:
random_array.size

15

In [45]:
random_array.shape

(3, 5)

In [61]:
random_array3= np.random.rand(5,3)

ValueError: low >= high

In [50]:
random_array3

array([[0.75073104, 0.39528767, 0.59213697],
       [0.7425464 , 0.12688171, 0.68644659],
       [0.9139342 , 0.14233411, 0.89638029],
       [0.54716463, 0.59391981, 0.32185789],
       [0.74560775, 0.26884219, 0.66490599]])

In [56]:
array5=np.random.randint(4,6,size=(2,5))

In [57]:
array5

array([[5, 5, 4, 5, 4],
       [4, 5, 4, 4, 5]])

In [62]:
a=np.random.seed()

In [63]:
a

#asdfsasdf

#sdf

# asdfasfd

In [65]:
np.unique(array5)

array([4, 5])

In [68]:
random_array=np.random.randint(4,6,size=(2,3))

In [67]:
random_array

array([[4, 4, 4, 4, 4],
       [4, 4, 5, 5, 5]])

In [78]:
a4= np.random.randint(10, size=(5,5,5,5))

In [79]:
a4

array([[[[7, 3, 6, 1, 6],
         [0, 7, 3, 0, 2],
         [4, 0, 4, 0, 1],
         [0, 8, 0, 4, 7],
         [9, 4, 7, 6, 4]],

        [[8, 0, 8, 1, 8],
         [9, 3, 9, 3, 9],
         [3, 6, 9, 7, 9],
         [2, 8, 1, 8, 0],
         [5, 7, 5, 1, 8]],

        [[5, 3, 4, 5, 5],
         [3, 0, 3, 5, 4],
         [7, 0, 1, 9, 0],
         [6, 8, 4, 4, 6],
         [2, 8, 4, 7, 4]],

        [[0, 3, 2, 2, 6],
         [7, 0, 7, 7, 5],
         [9, 6, 6, 8, 5],
         [5, 8, 6, 3, 2],
         [6, 9, 7, 6, 0]],

        [[8, 6, 9, 1, 1],
         [9, 9, 7, 0, 7],
         [3, 2, 7, 8, 5],
         [6, 9, 4, 6, 2],
         [5, 8, 2, 0, 6]]],


       [[[5, 3, 3, 6, 9],
         [3, 9, 7, 5, 5],
         [4, 3, 1, 2, 1],
         [5, 3, 2, 7, 0],
         [1, 8, 8, 1, 0]],

        [[6, 4, 2, 7, 0],
         [0, 4, 4, 7, 7],
         [8, 6, 4, 3, 9],
         [3, 9, 5, 6, 6],
         [3, 7, 4, 4, 4]],

        [[2, 2, 6, 2, 6],
         [2, 4, 7, 1, 4],
         [8, 8, 1, 0, 

In [90]:
a4[:4,:2,:2,:4]

array([[[[7, 3, 6, 1],
         [0, 7, 3, 0]],

        [[8, 0, 8, 1],
         [9, 3, 9, 3]]],


       [[[5, 3, 3, 6],
         [3, 9, 7, 5]],

        [[6, 4, 2, 7],
         [0, 4, 4, 7]]],


       [[[0, 7, 9, 2],
         [5, 5, 2, 4]],

        [[7, 4, 7, 5],
         [4, 8, 3, 3]]],


       [[[5, 5, 9, 9],
         [5, 5, 3, 8]],

        [[3, 0, 5, 2],
         [6, 7, 8, 2]]]])